[pytest]

markers =
    ui_selenium: UI Selenium Tests
    ui_playwright: UI Playwright Tests
    cli: CLI Tests
    api: API Tests

addopts =
    -v -s -n auto --reruns 2
    --html=Reports/HTML_Report/report.html
    --alluredir=Reports/Allure_Report/Allure_Raw_Data
